# https://conda-forge.org/docs/maintainer/conda_forge_yml.html
azure:
  build_id: 5
  user_or_org: TileDB-Inc
  project_name: CI
channels:
  sources:
    - conda-forge
  targets:
    - ["tiledb", "main"]
conda_build:
  pkg_format: '2'
conda_forge_output_validation: False
github:
  user_or_org: TileDB-Inc
  branch_name: main
  tooling_branch_name: main
provider:
  linux_64: azure
  osx_64: None
  win_64: None
